[package]
name = "hexar"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hexar"
path = "src/main.rs"

[dependencies]
log = "0.4.22"
smallvec = { version = "1.14.0" }
env_logger = "0.11.5"
nalgebra = "0.33.0"
thiserror = "1.0.69"

[dev-dependencies]
serialport = "4.6.0"